config/routes.rb
Rails.application.routes.draw do
  root 'site#index'
  get '/end', to: 'site#end'
  post '/login', to: 'site#login'
  get '/logout', to: 'site#logout'
  get '/start', to: 'site#start'
  get '/expired', to: 'site#expired'

  resources :answers

  resources :users
end

app/models/answer.rb
class Answer < ActiveRecord::Base
    validates :user_id, presence: true
    validates :question_id, presence: true
    validates :word_id, presence: true
    validates :value, presence: true
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_and_belongs_to_many :words
  has_many :answers
end

app/models/user.rb
# Update user model to add new questions
class User < ActiveRecord::Base
  validates :name, presence: true
  validates :firstname, presence: true
  validates :age, presence: true
  validates :email, presence: true, uniqueness: { message: "Attention ce mail est déjà enregistré" }
  validates :gender, presence: true
  validates :quebeker, presence: true
  validates :yearsquebec, presence: false
  validates :mothertongue, presence: true
  validates :languages, presence: true
  validates :education, presence: true
  validates :highestscol, presence: true
  validates :question1, presence: true
  validates :question2, presence: true
  validates :neurotb, presence: false
  validates :psytb, presence: false
  validates :medoc, presence: false
end

app/models/word.rb
class Word < ActiveRecord::Base
  has_and_belongs_to_many :questions
  has_many :answers
  accepts_nested_attributes_for :answers, :reject_if => :all_blank
 
  # Update the question model as now one question displayed per word 
  def get_question(user_id)
    user = User.find(user_id)
    question_group_ids = user.student_group.question_group_ids

    valid_questions = []
    questions.each do | question |
      if question_group_ids.include?(question.group_id)
        valid_questions.append(question)
      end
    end
    return valid_questions
  end

end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  # GET /words/1
  # GET /words/1.json
  def show
  end

  def new
    @question = Question.find(session[:current_question_id])
    @word = Word.find(session[:current_word_id])
    @answer = Answer.new(
      user_id: session[:user_id],
      word_id: @word.id,
      question_id: @question.id)

    @rate = (session[:total_word] - session[:word_ids].size - 1) * 100.0 / session[:total_word]
    @timeRemaining = User.find(session[:user_id]).end_of_session - Time.now
    session[:expired] = false
    @timeWarning = false
    if @timeRemaining <= 0
      session[:expired] = true
    elsif @timeRemaining < 600 # 10 minutes
      @timeWarning = true
    end
    session[:answer_create_at] = Time.now
  end

  def create
    @answer = Answer.new(answer_params)
    @answer.word_id = session[:current_word_id]
    @answer.response_time = Time.new - Time.parse(session[:answer_create_at])
    if @answer.save
      if session[:expired]
        reset_session
        redirect_to '/expired'
      elsif session[:question_ids].size != 0
        session[:current_question_id] = session[:question_ids].shift
        redirect_to new_answer_path
      elsif session[:word_ids].size != 0
        word_id = session[:word_ids].shift
        session[:current_word_id] = word_id
        session[:question_ids] = Question.all.ids
        session[:current_question_id] = session[:question_ids].shift
        redirect_to new_answer_path
      else
        user = User.find(session[:user_id])
        user.stop = Time.now
        user.save
        reset_session
        redirect_to '/end'
      end
    else
      render action: 'answers', alert: 'Error'
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def answer_params
      params.require(:answer).permit(:value, :user_id, :question_id, :word_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    @user = User.new()
    if session[:start]
      redirect_to new_answer_path
    end
  end

  def login
    email = params[:user][:email]
    @user = User.find_by_email(email)
    if @user
      if @user.end_of_session != nil
        flash[:alert] = "L'adresse email #{email} a déjà participé au questionnaire. Si c'est une erreur, contactez labo.brambati@gmail.com"
      else
        session[:user_id] = @user.id
        session[:user_name] = @user.name
      end
    else
      flash[:alert] = "L'adresse email #{email} n'a pas été trouvé, êtes vous bien enregistré"
    end
    redirect_to '/'
  end

  def logout
    reset_session
  end

  def start
    @user = User.find(session[:user_id])
    @user.start = Time.now
    @user.end_of_session = Time.now + 90.minutes
    @user.save
    session[:user_id] = @user.id
    session[:user_name] = @user.name
    group_id = @user.id.modulo(12) + 1
    session[:word_ids] = Word.where(group_id: group_id).pluck(:id).shuffle
    session[:total_word] = session[:word_ids].size
    word_id = session[:word_ids].shift
    session[:current_word_id] = word_id
    session[:question_ids] = Question.all.ids
    session[:current_question_id] = session[:question_ids].shift
    session[:start] = @user.start
    session[:end_of_session] = @user.end_of_session
    redirect_to new_answer_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit]

  # GET /users/new
  def new
    @user = User.new
    if session[:user_id]
      redirect_to new_answer_path
    end
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    if @user.save
        session[:user_id] = @user.id
        session[:user_name] = @user.name
        redirect_to '/'
    else
      respond_to do |format|
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(
        :name, :firstname, :age, :email, :gender, :quebeker,
        :yearsquebec, :mothertongue, :languages, :education, :highestscol,
        :question1, :question2, :neurotb, :psytb, :medoc)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= simple_form_for(@answer) do |f| %>

  <div class="progress large-12 success round">
    <span class="meter" style="width: <%= @rate %>%"></span>
  </div>

  <% if @timeWarning %>
    <div class="alert-box alert">Il vous reste moins de 10 minutes pour compléter votre session</div>
  <% end %>

  <% if @error %>
    <div class="alert-box alert">Veuillez répondre à toutes les questions</div>
  <% end %>

  <h1 class="large-10 word text-center"><%= @word.name %></h1>
  <h2 class="large-10 question text-center"><%= @question.name %></h2>
  <div class="large-2 text-center columns question_answer question-label"><%= @question.min %></div>
  <div class="large-6 columns question_answer">
      <%= f.input :value, :as => :range, :label => false, input_html: { class: 'large-12' } -%>
      <%= f.input :user_id, :as => :hidden, :input_html => {:value => session[:user_id]} -%> 
      <%= f.input :question_id, :as => :hidden, :input_html => {:value => @question.id} -%> 
  </div>
  <div class="large-2 text-center columns question_answer question-label"><%= @question.max %></div>
  <div class="large-12 columns"></div>
  <div class="form-actions">
    <%= f.button :submit, "Suivant", :class => "success right" %>
  </div>  
<% end -%>

app/views/answers/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "foundation-rails" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "vendor/modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="row">
      <div class="large-12 columns">

        <!-- Navigation -->

        <div class="row">
          <div class="large-12 columns">

            <nav class="top-bar">
              <ul class="title-area">
                <li class="name">
                  <h1><a href="/">Evaluation en ligne </a></h1>
                </li>
              </ul>

              <section class="top-bar-section">
                <ul class="left title-area">
                  <li class="divider"></li>
                  <li><a> <%= session[:user_name] %></a></li>
                </ul>

                <!-- ul class="right title-area">
                  <li class="divider"></li>
                  <li><a href="/logout">Logout</a></li>
                </ul -->
              </section>

            </nav>
            <!-- End Top Bar -->
          </div>
        </div>
        <!-- End Navigation -->

        <!-- Content -->
        <div class="row">
          <div class="large-12 columns">
            <%= yield %>
          </div>
        </div>
        <!-- End Content -->

        <!-- Footer -->
        <footer class="row">
          <div class="large-12 columns"><hr />
            <div class="row">
              <div class="large-6 columns">
                <p>&copy; Copyright Sébastien BEAU, licence copyleft : AGPLv3.</p>
              </div>
           </div>
          </div>
        </footer>
        <!-- End Footer -->

      </div>
    </div>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/site/end.html.erb
<div class="row">

  <div class="large-12 columns">
    <h1>C'est fini ! Merci de votre participation !</h1>

    <p class='instruction'>
    <% if session[:expired] %> <!-- not working: session not in the scope of view.site ? -->
      Explication temps expiré
    <% else %>
      Vous recevrez un courriel contenant la carte cadeau dans les prochains jours.
    <% end %>
    </p>

    <p class='instruction'>
      Si vous avez des questions, voici notre courriel : labo.brambati@gmail.com
    </p>
  </div>

</div>

app/views/site/expired.html.erb
<div class="row">

  <div class="large-12 columns">
    <h1>C'est fini ! Merci de votre participation !</h1>

    <p class='instruction'>
      Explication temps expiré
    </p>

    <p class='instruction'>
      Si vous avez des questions, voici notre courriel : labo.brambati@gmail.com
    </p>
  </div>

</div>

app/views/site/index.html.erb
<div class="row">
  <div class="large-12 columns">

    <% unless session[:user_id] %>
      <p class='instruction'>
      Vous allez participer à une étude qui évalue votre ressenti subjectif par rapport à des mots en français.
      </p>

      <p class='instruction'>
      Le temps de votre participation est d’une durée maximale d’une heure et demie.
      </p>

      <p class='instruction'>
      Seuls les participants qui auront terminé tout le questionnaire recevront la carte cadeau.
      </p>

      <p class='instruction'>
      Ne vous connectez pas immédiatement au site du questionnaire si vous n’êtes pas sûr d’avoir une heure et demie de temps libre sans aucune distraction (seul dans une pièce, ambiance calme, pas de téléphone, etc…)
      </p>

      <%= link_to "S'enregistrer", new_user_path, :class => "button button-large" %>

      <p class='instruction'>
      Si vous êtes déjà enregistré, renseignez votre courriel :
      </p>

      <% flash.each do |key, value| %>
        <%= content_tag :div, value, class: "alert-box #{key}" %>
      <% end %>

      <%= simple_form_for(@user, :url => login_path) do |f| %>
        <%= f.input :email, label: 'email' %>
        <%= f.button :submit, "Commencer le questionnaire", :class => "success right" %>
      <% end %>
    <% else %>

      <p class='instruction'>
      Ne vous connectez pas immédiatement au site du questionnaire si vous n’êtes pas sûr d’avoir une heure et demie de temps libre sans aucune distraction (seul dans une pièce, ambiance calme, pas de téléphone, etc…)
      </p>

      <%= link_to "Faire le questionnaire plus tard", logout_path, :class => "button button-large" %>

      <h1>Consignes</h1>

      <h2>Familiarité avec le concept</h2>

      <p class='instruction'>
      Vous êtes invité(e) à donner votre estimation sur le degré auquel vous pensez connaitre ou être en contact avec le concept évoqué par un mot.
      </p>

      <p class='instruction'>
      Par exemple, si vous vous sentez très familier avec le concept qu’évoque le mot « kiwi », vous voyez parfaitement à quoi ressemble un « kiwi », quel goût il a, sa texture, etc., vous déplacerez le curseur sur le côté droit de la barre qui indique que c’est un concept extrêmement familier.
      </p>

      <p class='instruction'>
      Au contraire, si le concept évoqué par un mot vous est moins familier, comme le mot « inukshuk », dans ce cas-là vous déplacerez le curseur sur le côté gauche de la barre qui indique que c’est un concept extrêmement peu familier.
      </p>

      <p class='instruction'>
      Faite défilez le curseur sur la barre (ou à une de ses extrémités) à l’endroit qui représente le mieux votre réponse. Par exemple, si vous jugez votre familiarité très forte, vous placerez votre curseur très proche de l’extrémité positive (voire sur celle-ci). Si vous jugez, par contre, que la familiarité est très faible, vous placerez votre curseur très proche de l’extrémité négative (voire sur celle-ci). Si vous estimez qu'elle est moyenne, vous placerez votre curseur aux environs du milieu de la barre, etc.
      </p>

      <h2>Valence émotionnelle</h2>

      <p class='instruction'>
      Évaluez la dimension émotionnelle d’un mot en indiquant si le mot lu renvoie à une émotion positive ou négative ou s’il ne renvoie à aucune émotion, autrement dit qu’il est neutre. Le but ici est d’évaluer à quel point ce mot évoque une émotion en le lisant. Vous estimerez alors  l’émotion sur une échelle allant d’extrêmement négative à extrêmement positive.
      </p>

      <p class='instruction'>
      Par exemple, si le mot « noir » vous provoque une émotion très négative, vous déplacerez le curseur sur le côté gauche de la barre qui est plus négatif. Mais si le mot n’évoque aucune émotion et vous vous sentez neutre par rapport à ce mot, vous placerez le curseur à l’aide de la souris au milieu de la barre.
      </p>

      <p class='instruction'>
      Si par exemple, le mot « blanc » vous évoque une émotion très positive, vous déplacerez le curseur sur le côté droit de la barre qui est plus positif. Mais si le mot n’évoque aucune émotion et vous vous sentez neutre par rapport à ce mot, vous placerez le curseur à l’aide de la souris au milieu de la barre. 
      </p>

      <h2>Force perceptuelle auditive et visuelle</h2>

      <p class='instruction'>
      Vous êtes invité(e) à estimer l’expérience perceptuelle que vous avez eue avec un concept. Chacun a vécu différemment son expérience sensorielle vis-à-vis des connaissances. Un mot comme « chien » pourrait avoir une force perceptuelle <b>auditive</b> plus forte que le mot « tortue », car vous avez souvent entendu le chien du voisin aboyer, mais que vous n’avez jamais possédez de chien. Mais ce mot «chien » pourrait avoir aussi une force perceptuelle <b>visuelle</b> plus forte que le mot « hamster » si vous avez possédez un chien comme animal de compagnie et jamais de hamster. Si le mot vous évoque une représentation auditive ou visuelle très forte, vous déplacerez le curseur sur le côté droit de la barre indiquant une expérience extrêmement forte.
      </p>

      <p class='instruction'>
      Certains mots plus abstraits, comme « impossible », peuvent être reliés à des représentations concrètes dans le vécu personnel (images, sons, etc…). Vous pouvez relier les mots abstraits à des expériences personnelles en rapport avec ces mots. Il est possible également que ces mots n’évoquent pas particulièrement des sons ou des images, et vous placerez alors le curseur vers le côté gauche de la barre.
      </p>

      <%= link_to "Commencer maintenant", start_path, :class => "button button-large" %>
    <% end %>

  </div>
</div>

app/views/site/logout.html.erb
<div class="row">

  <div class="large-12 columns">
    <h1>Vous êtes enregistré, veuillez vous reconnecter plutard pour faire le questionnaire !</h1>

    <p class='instruction'>
      Si vous avez des questions, voici notre courriel : labo.brambati@gmail.com
    </p>
  </div>

</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>

<div class="row">
  <div class="large-12 columns">
    <div class="form-inputs">
      <div class="large-6 columns">
        <%= f.input :name, label: 'Nom' %>
        <%= f.input :firstname, label: 'Prénom' %>
        <%= f.input :email, label: 'Votre courriel', error_html: { id: 'email_error'} %>
        <%= f.input :age %>
        <%= f.input :gender, collection: [:male, :female], label: 'Sexe'%>
        <%= f.input :quebeker, collection: [:oui, :non], label:"Êtes vous né(e) au Québec ?" %>
        <%= f.input :yearsquebec, label: "Combien d'années vécues au Québec ?" %>
        <%= f.input :mothertongue, label:"Langue maternelle ?" %>
        <%= f.input :languages, label:"La ou les langue(s) parlée(s) depuis la naissance ?" %>
        <%= f.input :education, label:"Années de scolarité ?" %>
        <%= f.input :highestscol, label:"Plus haut niveau d'études complétées ?" %>
      </div>
      <div class="large-12 columns">
        <div class="large-12 columns"><h3>Comment jugez-vous votre vue (avec correction) ?</h3></div>
        <div class="large-12 columns">
        <%= f.collection_radio_buttons :question1,
                [[1, 'mauvaise'], [2, 'satisfaisante'], [3, 'bonne'], [4, 'excellente']],
                :first,
                :last,
                collection_wrapper_tag: 'div',
                required: true
              -%>
        </div>

        <div class="large-12 columns"><h3>Comment jugez-vous votre audition (avec correction) ?</h3></div>
        <div class="large-12 columns">
        <%= f.collection_radio_buttons :question2,
                [[1, 'mauvaise'], [2, 'satisfaisante'], [3, 'bonne'], [4, 'excellente']],
                :first,
                :last,
                collection_wrapper_tag: 'div',
                required: true
              -%>
        </div>
      </div>

      <div class="large-12 columns">
        <div class="large-12 columns">
          <h3>Antécédents neurologiques (traumatisme crânien, épilepsie, migraine chronique ...) ?</h3>
          <%= f.input :neurotb, label: false %>
          <h3>Antécédents psychologiques (dépression, anxiété, trouble bipolaire ...) ?</h3>
          <%= f.input :psytb, label: false %>
          <h3>Médication actuelle (autre que la pilule contraceptive) ?</h3>
          <%= f.input :medoc, label: false %>
        </div>
      </div>

      <div class="form-actions large-12 columns">
      <%= f.button :submit, "Valider", :class => "success right" %>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/users/new.html.erb
<h1>Veuillez vous enregistrer</h1>

<%= render 'form' %>

app/views/words/answers.html.erb
<%= simple_form_for(@word) do |f| %>

  <div class="progress large-12 success round">
    <span class="meter" style="width: <%= @rate %>%"></span>
  </div>

  <% if @timeWarning %>
    <div class="alert-box alert">Il vous reste moins de 10 minutes pour compléter votre session</div>
  <% end %>

  <% if @error %>
    <div class="alert-box alert">Veuillez répondre à toutes les questions</div>
  <% end %>

  <h2 class="question"><%= @question.name % @word.name %></h2>
  <div class="large-2 columns question_answer question-label"><%= @question.min %></div>
  <div class="large-6 columns question_answer">
    <%= f.simple_fields_for :answers, @question.answers.find_or_initialize_by(
      user_id: session[:user_id],
      word_id: @word.id,
      question_id: @question.id) do |a| -%>

      <%= a.input :value, :as => :range, :label => false, input_html: { class: 'large-12' } -%>
      <%= a.input :user_id, :as => :hidden, :input_html => {:value => session[:user_id]} -%> 
      <%= a.input :question_id, :as => :hidden, :input_html => {:value => @question.id} -%> 
    <% end -%>
  </div>
  <div class="large-2 columns question_answer question-label"><%= @question.max %></div>
  <div class="large-12 columns"></div>
  <div class="form-actions">
    <%= f.button :submit, "Suivant", :class => "success right" %>
  </div>  
<% end -%>